#!/bin/sh
qemu-system-i386 -cpu 486 -m 256m -drive file=slackware.img,format=raw -drive file=fat:rw:share,format=raw,media=disk -net nic,model=ne2k_isa -net user,hostfwd=tcp::2300-:23 -display sdl -enable-kvm
