#!/bin/bash

for file in */ ; do 
  if [[ -d "$file" && ! -L "$file" ]]; then
    echo "Creating disk ${file%/}";
    mkdosfs -C ../vfloppy/${file%/} 1440  
    sudo mount ../vfloppy/${file%/}  ../vfloppy/mnt/
    sudo cp -r $file* ../vfloppy/mnt/
    sudo umount ../vfloppy/mnt/
  fi; 
done

